apiVersion: apps/v1
kind: Deployment
metadata:
  name: rental-api
  namespace: rental-mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rental-api
  template:
    metadata:
      labels:
        app: rental-api
    spec:
      containers:
        - name: rental-api
          image: rental_price_mlops_ccds-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"