apiVersion: v1
kind: Service
metadata:
  name: rental-api-service
  namespace: rental-mlops
spec:
  selector:
    app: rental-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort