apiVersion: v1
kind: Service
metadata:
  name: rental-api
  namespace: rental-mlops
  labels:
    app: rental-api
spec:
  type: ClusterIP
  selector:
    app: rental-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
